import type { useBattleSystem } from "@/hooks/battle/useSystem";
import type { useNpcAI } from "@/hooks/battle/npc/useAi";
import type { useChargeAttack } from "@/hooks/battle/charge/useAttack";
import type { useArturOraPunch } from "@/hooks/battle/player/characters/srGuaxinim/useArturOraPunch";
import type { useArturKillerQueen } from "@/hooks/battle/player/characters/srGuaxinim/useArturKillerQueen";
import type { useKokusenAnimation } from "@/hooks/battle/player/characters/Natsuki/useKokusenAnimation";
import type { useSpecialIntro } from "@/hooks/battle/useSpecialIntro";
import type { usePlayerSpecialProjectile } from "@/hooks/battle/player/usePlayerSpecialProjectile";
import type { useCoffinAnimation } from "@/hooks/battle/summon/useCoffinAnimation";
import type { useNpcSetup } from "@/hooks/battle/npc/useSetup";
import type { SummonedNpc } from "@/utils/types/npc/npc";
import type { CharactersProgress } from "@/data/characters/defaultProgress";
import type { ReplayData } from "@/utils/types/replay";
import type { NavigateFunction } from "react-router";

type Battle = ReturnType<typeof useBattleSystem>;
type Npc = ReturnType<typeof useNpcAI>;

export type BattleSceneApi = {
  player: Player;
  npc: Npc;
  battle: Battle;
  npcStats: ReturnType<typeof useNpcSetup>["npcStats"];
  npcLevel: number;
  summons: SummonedNpc[];
  allies: SummonedNpc[];
  coffins: ReturnType<typeof useCoffinAnimation>["coffins"];
  pet: Battle["pet"];
  petSkill: Battle["petSkill"];
  charProgress: CharactersProgress[CharacterId];
  missingXp: number;
  xpReward: number;
  lastRewards: unknown;
  showVictory: boolean;
  showDefeat: boolean;
  showOutro: unknown;
  showHighlight: boolean;
  highlightData: unknown;
  handleCloseHighlight: () => void;
  handleCloseOutro: () => void;
  handleRetry: () => void;
  handleContinue: () => void;
  navigate: NavigateFunction;
  showIntro: boolean;
  skipIntro: () => void;
  skipVictoryDelay: boolean;
  comboCount: number;
  comboRank: string;
  comboProgress: number;
  nextRank: string | null;
  charge: ReturnType<typeof useChargeAttack>;
  defeatElapsed: number;
  victoryElapsed: number;
  bestTime: number;
  defeatProgress: number;
  grabFlipped: boolean;
  getReplayData: () => ReplayData | null;
  isRecording: boolean;
  training: boolean | undefined;
  controlsDisabled: boolean;
  showRetry: boolean;
  playerProjectile: ReturnType<typeof usePlayerSpecialProjectile>["playerProjectile"];
  killerQueen: ReturnType<typeof useArturKillerQueen>["killerQueen"];
  bombTargets: ReturnType<typeof useArturKillerQueen>["bombTargets"];
  killerQueenSprite: ReturnType<typeof useArturKillerQueen>["killerQueenSprite"];
  bombSprite: ReturnType<typeof useArturKillerQueen>["bombSprite"];
  explosionSprite: ReturnType<typeof useArturKillerQueen>["explosionSprite"];
  extraPunches: ReturnType<typeof useArturOraPunch>["punches"];
  extraPunchSprite: string;
  kokusenActive: ReturnType<typeof useKokusenAnimation>["kokusenActive"];
  kokusenFrame: ReturnType<typeof useKokusenAnimation>["kokusenFrame"];
  specialIntroActive: ReturnType<typeof useSpecialIntro>["specialIntroActive"];
  specialIntroCharacter: ReturnType<
    typeof useSpecialIntro
  >["specialIntroCharacter"];
  lootBags: import("@/utils/types/battle/loot").BattleLootBag[];
  lootActive: boolean;
  npcClass: NPCClass;
};
