import {
  sfx,
  transitionPath,
  battleDefault,
  receiveOrUnlock,
  marceloSoundPath,
  arturSoundPath,
  riquelmeSoundPath,
  emanuelSoundPath,
  playerSoundPath,
  xpLevelPath,
  useItemPath,
  npcSoundPath
} from "@/utils/paths";

export function createSounds() {
  return {
    win: battleDefault("win.mp3"),
    defeat: battleDefault("defeat.mp3"),
    run: battleDefault("run.mp3"),
    cantMove: playerSoundPath("/cantMove.mp3"),
    tryAgain: battleDefault("tryAgain.mp3"),
    receivedItem: receiveOrUnlock("receivedAnItem.mp3"),
    usedItem: useItemPath("usedAnItem.mp3"),
    deliciometroIsFull: battleDefault("deliciometroIsFull.mp3"),
    questUpdated: receiveOrUnlock("questUpdated.mp3"),
    levelUp: xpLevelPath("levelUp.mp3"),
    loading: new Audio(transitionPath("blink.mp3")),
    moveMenu: sfx("menu/move.mp3"),
    chooseYourCharacter: sfx("menu/chooseYourCharacter.mp3"),
    selectMenu: sfx("menu/select.mp3"),
    closeMenu: sfx("menu/close.mp3"),
    chargingAttack: playerSoundPath("chargingAttack.mp3"),
    chargeAttack: playerSoundPath("chargeAttack.mp3"),
    swordDeflected: marceloSoundPath("sword-deflected.mp3"),
    jhowsimarVemCa: npcSoundPath("jhowsimar/goHere.mp3"),
    preMarshadowSpecial: marceloSoundPath("preSpecial.mp3"),
    marshadowSpecial: marceloSoundPath("special.mp3"),
    getsugaTenshou: marceloSoundPath("getsugaTenshou.mp3"),
    statusLevelUp: xpLevelPath("statusLevelUp.mp3"),
    mugetsu: marceloSoundPath("mugetsu.mp3"),
    vastolordTransformation: marceloSoundPath("vastolordTransformation.mp3"),
    returningTime: arturSoundPath("returning-time.mp3"),
    honoredOne: riquelmeSoundPath("honored-one.mp3"),
    emanuelTeleport: emanuelSoundPath("teleport.mp3"),
    chargingKi: emanuelSoundPath("chargingKi.mp3"),
    throwGenkiDama: emanuelSoundPath("throwGenkiDama.mp3"),
    ORA: arturSoundPath("ORA!.mp3"),
    clap: arturSoundPath("clap.mp3"),
    prePalm: arturSoundPath("prePalm.mp3"),
    srGuaxinimDefeat: arturSoundPath("defeat.mp3"),
    blink: sfx("blink.mp3"),
    explosion: sfx("explosion.mp3"),
    natsukiSpecial: riquelmeSoundPath("special.mp3"),
    kokusen: riquelmeSoundPath("kokusen.mp3"),
    impact: sfx("impact.mp3"),
    slimitaJump: npcSoundPath("slimita/jump.mp3"),
    equip: new Audio(transitionPath("equip.mp3")),
    unequip: new Audio(transitionPath("unequip.mp3")),
    unlockedTitle: playerSoundPath("unlockedTitle.mp3"),
    eating: useItemPath("eating.mp3"),
    drinkingPotion: useItemPath("drinkingPotion.mp3"),
    jhowsimarJooj: npcSoundPath("jhowsimar/throw.mp3"),
    boom: npcSoundPath("slimita/boom.mp3"),
    gainXp: xpLevelPath("gainXp.mp3"),
    chestOpening: useItemPath("chestOpening.mp3"),
    goatJump: npcSoundPath("goat/jump.mp3"),
    hungryDeath: npcSoundPath("hungryDeath/giveMeAPlate.mp3"),
    bite: npcSoundPath("hungryDeath/bite.mp3"),
    vandinhaPunch: npcSoundPath("vandinhaFragment/punch.mp3"),
    whooshWind: npcSoundPath("maugrelo/whoosh-wind.mp3"),
    writing: npcSoundPath("maugrelo/writing.mp3"),
    stupid: npcSoundPath("maugrelo/stupid.mp3"),
    paperPreExplode: npcSoundPath("maugrelo/paperPreExplode.mp3"),
    groundPaperPreExplode: npcSoundPath("maugrelo/groundPaperPreExplode.mp3"),
    chapterSuspense: sfx("chapterSuspense.mp3"),
    slap: npcSoundPath("maugrelo/slap.mp3"),
    laser: npcSoundPath("maugrelo/laser.mp3"),
    throwPaper: npcSoundPath("maugrelo/throwPaper.mp3"),
    shieldStack: npcSoundPath("maugrelo/shieldStack.mp3"),
    breakDish: npcSoundPath("vandinhaFragment/breakDish.mp3"),
    hulk: npcSoundPath("hungryKing/hulk.mp3"),
    smash: npcSoundPath("hungryKing/smash.mp3"),
    summon: npcSoundPath("hungryKing/summon.mp3"),
    knifeAttack: npcSoundPath("maurao/knifeAttack.mp3"),
    knifeCut: npcSoundPath("maurao/knifeCut.mp3"),
  };
}
