const NPC_DISPLAY_NAMES: Record<string, string> = {
  vandinhaFragment: "Fragmento de Vandinha",
  trueVandinha: "Verdadeira Vandinha",
  slimita: "Slimita",
  hungryDeath: "Morto de Fome",
  hungryKing: "Rei Faminto",
  hungryDog: "Cachorro Faminto",
  hungryFish: "Peixe Faminto",
  hungryCow: "Vaca Faminta",
  hungryPig: "Porco Faminto",
  jhowsimar: "Jhowsimar",
  goat: "Bode",
  deise: "Deise",
  denis: "Denis",
  srGuaxinim: "Sr. Guaxinim",
  neimito: "Neimito",
  planetarySisters: "Irmãs Planetárias",
  manim: "Manim",
  maurao: "Maurão",
  maugrelo: "Maugrelo",
  lupita: "Lupita",
  duque: "Cachorro de Riquelson",
  baiano: "Baiano",
  spiritMotocycler: "Motoqueiro Fantasma",
  tim: "Tim",
  muyMacho: "Muy Macho",
  fischer: "Fischer",
  leviathan: "Leviathan",
  figurantOfBaalCult: "Figurante do Culto de Baal",
  baal: "Baal",
  madame: "Madame",
  figurantOfMobyDickCult: "Figurante do Culto de Moby Dick",
  crocodile: "Crocodilo",
  elitCrocodile: "Crocodilo de Elite",
  mobyDick: "Moby Dick",
  yangKai: "Yang Kai",
  figurantOfDragonKingCult: "Figurante do Culto do Rei Dragão",
  ains: "Ains",
  dragonKing: "Rei Dragão",
  technoblade: "Technoblade",
  dummy: "Boneco de Treino",
};

export function getNpcDisplayName(npcType: string): string {
  return NPC_DISPLAY_NAMES[npcType] ?? npcType;
}
